build:
  builder: NIXPACKS

deploy:
  startCommand: npm start
  healthcheckPath: /
  restartPolicyType: ON_FAILURE
  restartPolicyMaxRetries: 10

environments:
  production:
    variables:
      NODE_ENV: production